globus-gladier/gladier

gladier/tools/dials/funcx_functions.py

Updates how the stills processing function deals with a tmp directory. It was unnecessarily creating a tmp dir when none were specified.

Fix tmp dir working

---

gladier/client.py

Globus group permissions set basic permissions around a flow, but acan be overrided
by a method get_flow_permission() for more complex use-cases

Allow setting globus group and subscription id

---

gladier/client.py
gladier/tests/conftest.py
gladier/tests/test_client_flows.py

For example, if a user added a new Transfer flow step, automate
would require the dependent tokens for the flow scope updated, and
the user would need to re-login. Gladier now detects the required
re-login required message from automate, and does so automatically
as long as auto_login=True on the gladier client.

fix: when user adds new AP to flow, Gladier now handles re-auth

---

docs/index.rst
docs/migration.rst
gladier/client.py
gladier/tests/conftest.py
gladier/tests/test_migrations.py
gladier/utils/config_migrations.py

So far, it includes the following:

Added Config Migration system + docs for upgrading

---

docs/index.rst

The previous text sounded more acedemic, but I had a hard time grasping
what was being said. I edited it to be more understandable for what
Gladier is and what it does.

Edited main index text for better readability

---

gladier/utils/flow_modifiers.py

All flow state fields are allowed, even if we don't have use-cases
for setting them.

feat: Expanded flow modifiers to accept all top level state fields

---

docs/gladier_tools/index.rst

docs: Add an explicit list of Gladier imports

---

.github/workflows/python-package.yml
docs/gladier_tools/index.rst

Fix a sphinx error with the docs not showing up. Add a docs build to each unit test to ensure it builds correctly.

Fix test docs

---

gladier/client.py
gladier/tests/test_utilities.py
gladier/utils/funcx_login_manager.py
requirements.txt

These changes upgrade to FuncX v1.
BREAKING CHANGE: Older funcx versions are no longer supported.

feat!: Upgrade to funcx v1

---

docs/gladier/overview.rst
docs/gladier/passing_payloads.py
docs/gladier/passing_payloads.rst

Passing parallel workloads with FuncX. This question comes up a lot, so it would really be good to have this in the docs!

docs: Added doc on passing FuncX Payloads

---

docs/gladier_tools/posix/index.rst
docs/gladier_tools/posix/shell_cmd.rst

This has been available in gladier tools for a while, but wasn't listed in the docs!

docs: Add missing shell command

---

docs/requirements.txt

Fix build problem with read-the-docs

docs: Fix requirements

---

gladier/client.py
gladier/managers/flows_manager.py
gladier/tests/test_client_flow_generation.py
gladier/tests/test_flows_manager.py

flow_schema can now be set on a GladierClient. Changes are tracked within the flow checksum and triggers re-deploys on edit changes.

feat: Add better support for flow schemas.

---

.github/workflows/python-package.yml

Downgrades version for running tests only

chore: Fix build with non-broken version of pyyaml

---

gladier/tools/globus/__init__.py
gladier/tools/globus/search.py

Add API State classes for search ingest and delete, with docs and code examples.

Add search state API classes

---

gladier/state_models.py

Per discussion on #263, change how the `next_state` value is initialized on `StateWithNextOrEnd`. There is a bit of verboseness to the code to properly pass typing.
This probably conflicts with other outstanding PRs as I started this branch from the current state of `main` which doesn't include #263 and thus does not have the renaming of `GladierBaseState` in place.

Change how next_state is initialized in StateWithNextOrEnd

---

gladier/managers/login_manager.py
gladier/tests/test_flows_manager.py

Dependent on #259 and https://github.com/globus-gladier/gladier/pull/268
When the flows client raised a dependent scope change and successfully
logged in, there was still a problem of the cached scope change not being
cleared after login, which made the login manager think it still hadn't
been added. This is now properly cleared after login so new flows can
be started.

Fix error after successful login due to a dependent scope change 

---

gladier/managers/compute_manager.py

Older versions of the globus_compute_sdk don't allow the custom dill strategies like this:
serialize.DillCodeSource()
This is a problem for running on Jupyterhub, or other older environments which require the older globus_compute_sdk versions.

fix: Add support for older globus_compute_sdk < 2.3.0

---

gladier/state_models.py
gladier/tests/test_builtin_tools.py
gladier/tools/builtins/choice_state.py
gladier/tools/builtins/wait.py
gladier/tools/globus/transfer.py
gladier/tools/helpers.py
gladier/utils/pydantic_v1.py

Support pydantic v2 package
Support for v1 is still allowed, if a project pins that dependency specifically

fix: Pydantic v2 support

---

gladier/__init__.py
gladier/client.py
gladier/managers/__init__.py
gladier/managers/login_manager.py
gladier/tests/conftest.py
gladier/tests/test_client.py
gladier/tests/test_client_auth.py
gladier/tests/test_client_flow_generation.py
gladier/tests/test_flows_manager.py
requirements.txt

This feature adds Globus App Auth to Gladier by default, replacing the old default using Fair Research Login. Fair Research Login is now deprecated and is discouraged.

Globus apps auth

---

gladier/managers/flows_manager.py

fix: Explicit Flow kwargs passed to flow manager not properly propagating
