globus-gladier/gladier

docs/clients_and_tools.rst, docs/glossary.rst, docs/index.rst, docs/installation.rst, docs/tools/gladier_example.py, docs/tools/index.rst
Added an installation page for showing new users how to install
Gladier, and a quick 5 minutes getting started guide. The purpose
behind these changes is to get users running Gladier as quickly
as possible, without explaining all the details of how Gladier works.
Once users can run the basic 'hello world' flow, we can teach them
about how various components can be customized
=> Added Installation/Getting Stared page, restructered things a bit

requirements.txt
funcx-0.2.2 is now on pypi, and it causes problems for some reason
=> Set funcx reqs to funcx==0.0.5 to fix permissions error running funcx

docs/flow_generation.rst, docs/flow_generation/fs_list_example.py, docs/flow_generation/fs_list_flow.json, docs/index.rst, gladier/__init__.py, gladier/client.py, gladier/decorators.py, gladier/exc.py, gladier/tests/conftest.py, gladier/tests/test_client_flow_generation.py, gladier/tests/test_data/gladier_mocks.py, gladier/tests/test_data/two_step_flow.json, gladier/tests/test_flow_generation.py, gladier/tests/test_flow_modifiers.py, gladier/tests/test_tool_flow_generation.py, gladier/utils/flow_generation.py, gladier/utils/flow_modifiers.py, gladier/utils/name_generation.py
Creating as a Draft, since this has some edge cases that aren't covered.
* As a quick hack to get this out, using `@generate_flow_definition` doesn't yet work on pre-defined GladierTool flows, only other automatically generated flows. That should probably be fixed before it's merged.
* **FIXED**
* Decorating Gladier Clients/Tools changes their type, and causes problems when Gladier checks each of the tools (So I lied, this might not be totally backwards compatible, but I think changes here should be pretty minor)
* **FIXED**
Check out a full copy/paste example here: https://github.com/NickolausDS/gladier/pull/1
Includes full test coverage and docs.
=> Added a prototype for automatic flow generation

gladier/client.py, gladier/config.py, gladier/tests/conftest.py, gladier/tests/test_client_flows.py
Previously, unsharable flow_ids and funcx ids were stored in the
gladier.cfg, which typically resides in the working directory where
the client exists. This has all been moved to the 'secrets' config.
Note: This also changes the location in the config where secrets are
stored so they will match up to client_ids. This will break all
previous logins, requiring re-auth by the user. Old credentials will
need to be purged manually by the user.
=> Move to private config

gladier/tests/test_client_flow_generation.py, gladier/tests/test_data/gladier_mocks.py, gladier/utils/flow_generation.py
Sometimes, two character typos are enough to break everything.
=> fix: Tools with more than two states would raise error with flow gen

gladier/__init__.py, gladier/utils/flow_generation.py, requirements.txt
Funcx 0.0.5 also depended on funcx-endpoint 0.0.3. funcx-endpoint
can be dropped in the next release, since adding it to gladier was
a convenience to ensure users didn't use the incompatible 0.2.3
package instead.
BREAKING CHANGE -- This will break all current funcx functions without
modification. Everyone will need to upgrade to the new funcX endpoint
package wherever they are executing functions. If manually generating
flow definitions, the following changes need to be made:
'ActionUrl': 'https://automate.funcx.org',
'ActionScope': 'https://auth.globus.org/scopes/b3db7e59-a6f1-4947-95c2-59d6b7a70f8c/action_all'
Additionally for funcx payloads the following
'func.$': '$.input.'
Needs to be changed to:
'function.$': '$.input.'
=> Funcx upgrade

.github/workflows/python-package.yml
Moving from master to main broke tests, this should fix it
=> chore: fix workflows -- run on new 'main' branch instead of master

gladier/client.py, gladier/tests/test_client_auth.py
This previously resulted in:
my_cli.login()
my_cli.logout()
my_cli.is_logged_in()  # Would still be true
This should now be fixed.
#111
=> fix: logout not properly clearing authorizers cache

docs/requirements.txt
Docstrings were not showing up due to the gladier-tools package not
being installed on the read-the-docs site. This adds the latest on
main so changes will immediately show up. We could set this back to
use the latest stable version in the future, but I think it will be
handy to see the latest changes immediately instead of waiting for a
stable release.
=> docs: Fix Gladier Tools docstrings

docs/examples/encrypt_and_transfer.py
* Added a default for the encrypt_key value
* Put the encrypted file into `my_encrypted_files` to disambiguate it better
from the other files
* Changed client name from CustomTransfer to EncryptAndTransfer and separated
out the run code for a bit better readability
=> docs: Fixed example failing if endpoints are left blank. Minor tweaks

docs/examples/tar_and_transfer.py
Commented out 'funcx_endpoint_compute' so Gladier will catch the missing
value and complain. This will ensure the user sets that value. Otherwise,
the flow will start and result in a "FlowFailed". Useful, since people
tend to run things 'as is' and are confused by any errors which are not
extremely specific.
=> docs: Added defaults to tar example, slight tweaks

gladier/client.py, gladier/utils/flow_generation.py
When an invalid flow modifier is set, Gladier will list the original
Tool or Client which isn't configured correctly
=> fix: Flow Modifier errors not propagating Client or Tool names

gladier/client.py
=> refactor: Remove old code for funcx < 0.1.0 compatibility

gladier/__init__.py
This wasn't properly checking funcx-endpoint, resulting in a warning
that printed to the user more than it should.
=> fix: Remove funcx-endpoint version check

gladier/client.py
Shortens the label to the last 62 chars plus '..' if the length is greater than 64.
=> Limits run label length to 64 chars

gladier/client.py, gladier/tests/test_migrations.py, gladier/utils/config_migrations.py
Only apply migrations when the config needs to be updated. This fixes the config getting corrupted when rapidly written to by many processes.
=> Only save config on migrate when migration needed

docs/examples/encrypt_and_transfer.py
FuncX doesn't know how to serialize pathlib vars into json. This
fixes that.
=> docs: Fix encrypt/transfer example not stringifying pathlib var

requirements.txt
Fair-research-login was implicitly added via funcx. FuncX will likely
remove this dependency later on, and Gladier will need to continue using
it.
=> chore: Update dependencies, add fair-research-login

gladier/client.py
Glaider will cache the flows-client when it is created for performance
if many calls need to take place. However, this is a problem if a new
login added a new scope to the client. This change simply removes the
flows client cache on re-login, so it can be re-cached later.
This isn't a perfect fix, but it does fix a problem when registering
and running flows for the first time.
=> fix: Possible flows client 401 due to client caching

gladier/client.py
This removes the docstring from the function registration step. When the docstring is too long (>10…24 characters) it causes an issue with registration as we place the description in a 1024 length varchar field. I'll raise this on the funcx side, but this is a fix for failed registration.
=> Removes the docstring during registration

gladier/decorators.py, gladier/tests/test_client_flow_generation.py, gladier/tests/test_data/gladier_mocks.py, gladier/utils/tool_chain.py
Fixed a problem where if @generate_flow_definition was used to
define a flow definition for a Tool, aliases wouldn't be applied
properly.
This was due to the decorator simply not passing args to the instances
it created.
Fix for #181
=> fix: Aliases not working with tools that use @generate_flow_definition

gladier/client.py
A slight mis-spelling of the flow permission names caused an error
when deploying flows. The error didn't seem to affect previously deployed
flows, where perms were already set, which caused this to slip past testing.
=> fix: Error on first time flow deployment if using group perms

gladier/storage/config.py, gladier/storage/tokens.py
The split of using the login manager as a separate configurable entity #192 means we now have two instances of config files writing to the same file. It was possible for the two configs to become out of sync with one another, and overwrite values with older versions. These changes ensure fresh configs are loaded any time there are changes so this can't happen.
Long term, I think we'll want to split these configs into separate files. Token storage will live in its own file with strict POSIX permissions, while general config (flow/funcx ids and checksums) will occupy a separate file. This will allow token storage and general storage to both be customized as needed.
=> Fix regression caused by login manager refactor

gladier/managers/funcx_manager.py
FuncX functions would not be registered on first time use due to authorizers possibly not being set. A request for the funcx client now triggers login if needed, and calls to register_function cannot be done without a live client.
=> Fix first time flow use

docs/gladier/overview.rst, docs/gladier/setup.rst
RTD doesn't work so well with pulling down binary files tracked with Git LFS. Ideally it could pull images as needed and access them locally without any additional steps. The problem is RTD build machines don't have git lfs clients, and most git lfs clients appear to authorize to github repos via SSH.
A much simpler solution here is to access lfs files through Github's media servers instead. They are accessible locally and via RTD. A downside is adding new files, but it's better than checking them in directly and keeps all of our glaider-related stuff in one repo.
=> docs: Fix images not showing up on RTD

gladier/client.py
re-add old login() method on Gladier client, to allow manually logging into Gladier instead of allowing for a missing authorizer event to trigger the flow.
=> fix: Add missing client ``login`` method

gladier/managers/flows_manager.py, gladier/tests/test_flows_manager.py
subscription_id will no longer be used for tying flows to a subscription. It should not be set on new flows.
=> fix: Deprecate subscription_id on Gladier Clients and flows

gladier/tests/test_client_flow_generation.py, gladier/utils/tool_chain.py
An issue with the ToolChain class caused it to re-use references to internal state within tool's flow definition, causing improper updates to tool flow definition dataq.
=> fix: Multiple instantiations of a Gladier Client raising errors

gladier/__init__.py
CallbackLoginManager was a feature in 0.8.0 and documented here: https://gladier.readthedocs.io/en/latest/gladier/custom_auth.html
The top level import has been fixed so that the custom script now works as expected.
=> fix: CallbackLoginManager not being a top-level import

docs/gladier/sdk_reference/gladier.rst, gladier/client.py, gladier/tests/test_client.py, gladier/tests/test_flows_manager.py
Method was removed with the new FlowManager class, which now handles deployment of the flow. The re-added method calls get_flow_id() on the manager class.
=> fix: erroneously removed `get_flow_id()` method on Gladier Clients

gladier/tests/test_client_flow_generation.py, gladier/tests/test_flow_traversal.py, gladier/tests/test_tool_flow_generation.py, gladier/utils/flow_generation.py, gladier/utils/tool_chain.py
Multiple FuncX Functions defined on a tool resulted in an improperly chained flow, causing the second function to not execute.
=> fix: flow generation bug when using multiple funcx functions on a tool

gladier/tests/test_tool_flow_generation.py, gladier/utils/flow_modifiers.py
Modifying "ActionUrl" would result in $.input.myvalue.
This has been fixed.
=> fix: State modifiers being given incorrect values for some items

gladier/client.py, gladier/managers/flows_manager.py
Docs were improperly moved with code for starting flows inside the Flows Manager class. However, flows aren't recommended nor documented for being started from the Flows Manager class, so these belong on the base Gladier Client.
=> docs: Move in-code docs from flows manager back to Gladier Client

gladier/client.py, gladier/managers/login_manager.py, gladier/storage/migrations.py, gladier/storage/tokens.py, gladier/tests/test_client_auth.py, gladier/tests/test_flows_manager.py
Users can specify client credentials inside their python environment, and Gladier will automatically create a new config file, separate from the user config file, and store all credentials and cached ids there. Specifying credentials looks like this:
```
export GLADIER_CLIENT_ID=my-client-id
export GLADIER_CLIENT_SECRET=my-client-secret
```
These changes also move ~/.gladier-secrets.cfg into `~/.gladier/` where each file is named according to the CLIENT_ID. This is either the confidential client id used, or the native id used (Whether built-in or custom). Migration code exists to move them into place for any older clients.
=> Confidential Client Support

gladier/client.py, gladier/tests/test_tool_flow_generation.py, gladier/utils/flow_modifiers.py
Using modifiers for old tools will no longer be allowed, and will
require tools to be updated to use the new compute function syntax. Requiring upgrades
fixes a problem where attempting to use modifiers will work, but cause a mismatch in inputs
causing unexpected failures when running flows. Instead of making this fully backwards compatible,
it's easier to just make people upgrade or downgrade to the correct versions.
For example, flows will need to be defined with the following:
```
'tasks': [{
'endpoint.$': '$.input.compute_endpoint',
'function.$': f'$.input.my_function_name_function_id',
'payload.$': '$.input',
}]
```
And all tools will need to define "compute_endpoints" and
"compute_functions" instead of "funcx_endpoint_compute/funcx_endpoint_non_compute"
and …
=> Fix legacy functions

gladier/managers/compute_manager.py
2.2.x switched to DillCode serialization instead of DillCodeSource by defalut, which caused functions run on 2.2.x to fail when using functions within Gladier Tools:
https://github.com/funcx-faas/funcX/blob/main/compute_sdk/globus_compute_sdk/serialize/concretes.py#L121
Switching to DillCodeSource manually fixes this, at least for now. There are nasty tradeoffs, such as potentially not being able to use functions within notebooks.
#254
=> fix: Function serialization failures using compute-sdk 2.2.3

gladier/managers/flows_manager.py, gladier/tests/conftest.py, gladier/tests/test_flows_manager.py
When dependent scopes change on flows, Gladier now properly detects the change and initiates a new login.
=> Fix Exception from improperly parsing the globus-sdk scope change error

gladier/client.py, gladier/managers/flows_manager.py
Subscription id has been deprecated since 0.8.x. Removing it here.
=> refactor!: Remove subscription id

docs/requirements.txt, gladier/client.py, gladier/managers/flows_manager.py, gladier/tests/conftest.py, gladier/tests/test_client_auth.py, gladier/tests/test_client_flow_generation.py, gladier/tests/test_flows_manager.py, gladier/tests/test_tool_flow_generation.py, requirements.txt
Remove the globus-automate-client dependency in favor of calling into the base globus-sdk instead
=> refactor!: Remove Globus-Automate-Client dependency

docs/gladier/sdk_reference/state_api/builtins.rst, docs/gladier/sdk_reference/state_api/compute.rst, gladier/tests/test_builtin_tools.py, gladier/tools/__init__.py, gladier/tools/builtins/choice_state.py, gladier/tools/builtins/wait.py
Some of the support type classes from the globus and builtin sub-modules weren't popped up to the top level gladier.tools module so using them still required imports from the sub-modules. For consistency, seems better to include them at the gladier.tools level.
=> Add some missing imports to gladier.tools

gladier/client.py, gladier/managers/flows_manager.py, gladier/tests/test_flows_manager.py
If progress runs for too long during a time of low load on the Flows service, it can sometimes return statuses fast enough that the service will run into the ping limit and begin to reject requests. This includes a small delay for each status ping to ensure this can't happen
=> fix: Gladier progress status checking sometimes running too fast

gladier/managers/flows_manager.py
When Gladier deployed or updated flows without schemas, there was a new error:
Additional properties are not allowed ('input' was unexpected)"
This was due to the default schema becoming invalid. This fixes that and allows schemas to be regitered with Gladier
=> fix: Exception when registering or updating flows

gladier/client.py, gladier/managers/compute_manager.py, gladier/tests/test_client.py
If a globus_group was defined for a Gladier Client, those will be applied on function registration to defined functions
=> feat: Compute functions now use globus_group on client for functions

gladier/client.py
Allow passing a custom compute manager into Gladier. This provides the capability to modify how internals of the compute manager behave, but does not yet document how users should do so. This will allow some prescriptive solutions until we figure out those details should properly behave.
=> Custom compute manager

gladier/client.py, gladier/managers/flows_manager.py, gladier/tests/test_flows_manager.py
This feature allows for passing arguments into the flow update and flow run methods. Flow kwargs will also prompt an update to the existing flow definition.
Any argument passed directly to the flow manager will supersede any arguments present on the flow, and will raise warnings instead.
=> feat: Allow passing extended flow and run kw args
